### ISSUE TITLE
Buscamos Arquitect@ de APIs!

### ISSUE THREAD

**Issue by rodowi** [mxabierto/hackea-el-sistema#1]
**Descripción**
Buscamos un *Arquitecto de Software* responsable de diseñar y planear la estrategia de una infraestructura eficiente, escalable, replicable y resiliente que permita atender la demanda ciudadana y de gobierno.

**Principales Tareas:**
- Planear, crear, y administrar APIs escalables y robustas, imagina un api.datos.gob.mx como [el API de Foursquare](https://developer.foursquare.com/).
- Trabajar junto a desarrolladores y DevOps para el diseño y desarrollo de APIs.
- Definir las políticas y la operación del monitoreo, y resolución de problemas con las APIs; imagina un status.datos.gob.mx, como [status.github.com](https://status.github.com/).
- Diseñar y conducir pruebas de stress, de alta disponibilidad y de prueba de concepto.

**Experiencia:**
- Has colaborado en proyectos open source
- Linux es tu casa
- Estas familiarizado con Amazon AWS / EC2 / S3, y en general con PaaS, IaaS, VPS
- Quieres que el mundo entero tenga REST APIs
- Utilizas algún lenguaje dinámico como Python, Ruby o compilados que se sientan dinámicos como Go
- Dominas el shell
- Has utilizado diferentes RDBMS como PostgreSQL, y NoSQL como MongoDB

**Bonus:** NewRelic, CI, Scala + Akka, Go, Node.js, Apache Cassandra.

**Comment by carlosmaya** [comment]
hola, estoy leyendo sobre la convocatoria y me gustaría unirme al grupo, estoy aplicando en este perfil, pero creo que hay varios bastante interesantes en los que bien podría colaborar 

mi página personal es

http://carlosmaya.mx

va también la liga para descargar mi curriculum 

http://carlosmaya.mx/profile/carlosmaya.pdf

un saludo!!

**Comment by rodowi** [comment]
Gracias @carlosmaya! Te acabo de escribir un correo para tener una llamada.
