### ISSUE TITLE
Buscamos Ingenier@ de Datos!

### ISSUE THREAD

**Issue by rodowi** [mxabierto/hackea-el-sistema#2]
**Descripción**
Buscamos alguien capaz de procesar grandes cantidades de datos, estandarizarlos, y transformarlos en formatos abiertos estructurados para que sean del mayor beneficio para la sociedad y proyectos de alto impacto.

**Principales Tareas:**

- Extraer GBs de datos de todo tipo de sistemas (algunos legacy y no documentados).
- Administrar eficientemente diferentes bases de datos.
- Estandarizar datos y transformarlos bajo esquemas interoperables y estándares.
- Coordinarte con DevOps, data scientists y desarrolladores para hacer proyectos de alto impacto.

**Experiencia:**

- Le mueves a Python, Java, o C++
- Puedes armar queries complejos en SQL y NoSQL
- Haz utilizado sistemas de procesamiento de datos como Hadoop, Hive, o Spark

**Bonus:** Conoces de data-science toolkits en R y Python.

**Comment by jrn1989** [comment]
Hola, me parece una iniciativa muy interesante y estaría interesado en colaborar, aunque mi perfil esta más orientado hacia *Data Science* que *Data Engineer*. Si en algún momento necesitan a uno, espero ser considerado :))

[CV](https://drive.google.com/file/d/0B6rdOeuAc8I3TlhPWHZ6eHdpNHM/view?usp=sharing)

Saludos

**Comment by rodowi** [comment]
Gracias @jrn1989 

Data scientists no están en la lista, pero también buscamos :smile: 

Te acabo de escribir un correo para ver si tenemos una llamada en la semana. Saludos!
